### ISSUE TITLE
(URGENT) Parsing of ISO/IEC Directives necessary

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#57]
We have new documents in the relaton-data-iso repo and pubis-iso fails with the IDs like `ISO IEC DIR 1`
https://github.com/relaton/relaton-iso/runs/6880704298?check_suite_focus=true#step:6:249

All new IDs:
- `ISO/IEC DIR 1` or reference `ISO IEC DIR 1`
- `ISO/IEC DIR 1 ISO SUP` or reference `ISO IEC DIR 1 ISO SUP`
- `ISO/IEC DIR 2 ISO` or reference `ISO IEC DIR 2 ISO`
- `ISO/IEC DIR JTC 1 SUP` or reference `ISO IEC DIR JTC 1 SUP`

**Comment by ronaldtse** [comment]
@andrew2net will provide the full list but they are ones like:

## ISO/IEC Directives, Part 1

* ISO/IEC DIR 1
* ISO/IEC DIR 1:2022
* ISO/IEC Directives Part 1
* ISO/IEC Directives, Part 1
* ISO/IEC Directives, Part 1:2022

## ISO/IEC Directives, Part 2

* ISO/IEC DIR 2
* ISO/IEC DIR 2:2021
* ISO/IEC Directives Part 2
* ISO/IEC Directives, Part 2
* ISO/IEC Directives, Part 2:2021

## ISO/IEC Directives IEC Supplement

* ISO/IEC DIR IEC SUP
* ISO/IEC Directives, IEC Supplement:2022

## ISO/IEC Directives, Part 1 -- Consolidated ISO Supplement

https://www.iso.org/sites/directives/current/consolidated/index.xhtml

* ISO/IEC DIR ISO SUP
* ISO/IEC DIR 1 ISO SUP
* ISO/IEC DIR 1 ISO SUP:2022
* ISO/IEC DIR 1 ISO SUP Edition 13
* ISO/IEC DIR 1 ISO SUP Ed 13
* ISO/IEC Directives, Part 1 -- Consolidated ISO Supplement

## ISO/IEC Directives, JTC 1 Supplement:2021

* ISO/IEC Directives, JTC 1 Supplement:2021
* ISO/IEC DIR JTC 1 SUP:2021
* ISO/IEC DIR JTC 1 SUP

## Combined

* ISO/IEC Directives, Part 1:2022 + IEC Supplement:2022
* ISO/IEC DIR 1:2022 + IEC SUP:2022

**Comment by mico** [comment]
@ronaldtse what is the "Directives" documents? Is it another document type? Like "TR", "TS", "IWA"?
Or is it something like technical committee documents? Like https://github.com/metanorma/pubid-iso/issues/41 this one.
Moreover, I found "JTC" in the part of PubID of document mentioned above is the type of "TC" documents, does it have a connection?

Trying to figure out how to build parser better, no it doesn't fit perfectly in normal PubIDs nor TC-PubIDs because of JTC type which now only exist for TC-PubIDs.

**Comment by ronaldtse** [comment]
These are a special type of ISO and IEC documents called the Directives.

ISO and IEC share the "ISO/IEC Directives", which is a set of documents explaining the processes of both organizations.
* The Directives has 2 parts, Part 1 and Part 2.
* ISO and IEC each have an additional "supplement" to the Directives
* ISO has a "Consolidated ISO supplement" on top of Directives Part 1.
* IEC has an "IEC Supplement" on top of the Directives as a whole.

> Or is it something like technical committee documents? Like https://github.com/metanorma/pubid-iso/issues/41 this one.

I consider the Directives as a different class of document from other document types and TC documents, just because their numbering scheme and naming scheme are different.

> Moreover, I found "JTC" in the part of PubID of document mentioned above is the type of "TC" documents, does it have a connection?

The "ISO/IEC JTC 1" is a committee of both ISO and IEC (it is a "joint" TC). They have their own "JTC 1 Supplement" to the "ISO/IEC Directives".

This is similar to the ISO/TC 184/SC 4 Supplementary Directives:
https://github.com/relaton/relaton-data-iso/blob/0ce3afcac2162edfddb947bd132d64fa55bf691a/data/ISO_TC_184_SC_4_N3493.yaml

> Trying to figure out how to build parser better, no it doesn't fit perfectly in normal PubIDs nor TC-PubIDs because of JTC type which now only exist for TC-PubIDs.

This is a good point. I think the Directives are a separate "class" of documents.
* We now have 3 "classes" of schemes:
  * Document types (TS, TR ...)
  * TC documents
  * Directives

**Comment by ronaldtse** [comment]
@mico I'm not sure if #58 fully parses all the combinations listed in https://github.com/metanorma/pubid-iso/issues/57#issuecomment-1157559404 . Can we have a txt file that lists them out that ensure they are parsed in RSpec? Thanks.

**Comment by mico** [comment]
> @mico I'm not sure if #58 fully parses all the combinations listed in [#57 (comment)](https://github.com/metanorma/pubid-iso/issues/57#issuecomment-1157559404) . Can we have a txt file that lists them out that ensure they are parsed in RSpec? Thanks.

You are right.
Edition parsing, organization-specific supplement and combined document are missing.
Do we need to parse long form? Like "ISO/IEC Directives Part 1" / "ISO/IEC Directives, Part 1 -- Consolidated ISO Supplement"?

**Comment by mico** [comment]
> * ISO/IEC DIR IEC SUP
Supplement without document number? Should I use some default number? (Like 1)

**Comment by ronaldtse** [comment]
This one means it is the "IEC Supplement to the ISO/IEC Directives (both parts)".

**Comment by ronaldtse** [comment]
> > @mico I'm not sure if #58 fully parses all the combinations listed in [#57 (comment)](https://github.com/metanorma/pubid-iso/issues/57#issuecomment-1157559404) . Can we have a txt file that lists them out that ensure they are parsed in RSpec? Thanks.
> 
> 
> 
> You are right.
> 
> Edition, organization-specific supplement and combined document parsing are missing.
> 
> Do we need to parse long form? Like "ISO/IEC Directives Part 1" / "ISO/IEC Directives, Part 1 -- Consolidated ISO Supplement"?

Yes we should support long form and those other attributes.

**Comment by ronaldtse** [comment]
Interestingly, the "ISO Supplement " is only to Part 1, but the "IEC Supplement" is to both parts. So we need to parse them correctly.

**Comment by mico** [comment]
> * ISO/IEC DIR 1 ISO SUP Edition 13
> * ISO/IEC DIR 1 ISO SUP Ed 13

Supplement's edition?

**Comment by ronaldtse** [comment]
@mico yes, edition of the Supplement:
https://www.iso.org/sites/directives/current/consolidated/index.xhtml
<img width="618" alt="Screenshot 2022-06-22 at 5 20 24 PM" src="https://user-images.githubusercontent.com/11865/174980241-915dbba7-3d09-4caf-94b2-0773288f3550.png">

**Comment by mico** [comment]
> * ISO/IEC DIR 1:2022 + IEC SUP:2022

Is it not the same as "ISO/IEC DIR 1:2022 IEC SUP:2022"? Or even "ISO/IEC DIR 1 IEC SUP:2022"?

**Comment by ronaldtse** [comment]
@mico no, it is a combination of two documents placed into one. IEC has this notation of "+" where it joins two documents.

**Comment by mico** [comment]
> @mico no, it is a combination of two documents placed into one. IEC has this notation of "+" where it joins two documents.

The second document, "IEC SUP:2022" don't have "DIR" type or number. Is it IEC published document without number with supplement applied?

**Comment by ronaldtse** [comment]
"IEC SUP:2022" is the short name for: "ISO/IEC Directives, IEC Supplement:2022"

https://www.iec.ch/news-resources/reference-material
<img width="965" alt="Screen Shot 2022-12-08 at 4 40 28 PM" src="https://user-images.githubusercontent.com/11865/206399286-a60a715c-61a0-41d0-91bf-cf1cefd88125.png">
